spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: 192.168.1.12
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    com.shuyuan.judd.oauth: info
    spring:
      shuyuan:
        judd:
          base:
            utils: info

com:
  shuyuan:
    judd:
      fundation:
        ribbon:
          NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
          ServerListRefreshInterval: 5000